version: '4'
services:
  mysql:
   image: mysql:8.3.0
   container_name: inventory-mysql
   environment:
    MYSQL_ROOT_PASSWORD: mysql
   ports:
    - "3308:3306"
   volumes:
    - ./mysql:/var/lib/mysql
    # docker-entrypoint es  el comando que se ejecuta cuando el contenedor este andando, lo uso para ejecutar el SQL de inicializacion
    - ./docker/mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql